title: "[Feature Request] "
labels: ["enhancement", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        
        Thank you for contributing to CronAI! Please provide details about the feature you'd like to see.
        
        **Note:** For bug reports, please use the issue tracker instead.
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see implemented
      placeholder: A clear and concise description of the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or pain point
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: How would you implement this feature?
      placeholder: Your ideas on implementation approach
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Other ways to solve this problem
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - Critical for my use case
        - Medium - Would be very helpful
        - Low - Nice to have
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Feature Type
      options:
        - label: New functionality
        - label: Enhancement to existing feature
        - label: Performance improvement
        - label: Developer experience
        - label: Documentation