title: "[RFC] "
labels: ["rfc", "discussion", "architecture"]
body:
  - type: markdown
    attributes:
      value: |
        ## Request for Comments (RFC)
        
        Use this template to propose significant changes to CronAI's architecture, API, or core functionality.
        
        RFCs help us make thoughtful decisions about the project's direction.
  - type: input
    attributes:
      label: RFC Title
      description: A concise title for your proposal
      placeholder: "e.g., Plugin Architecture for Response Processors"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: Brief overview of the proposal (2-3 sentences)
      placeholder: What are you proposing in a nutshell?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this change needed?
      placeholder: |
        - What problem does this solve?
        - What use cases does it enable?
        - Why is the current solution inadequate?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed Design
      description: The meat of the proposal
      placeholder: |
        Explain your design in detail:
        - API changes
        - Implementation approach
        - Code examples
        - Configuration changes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: Why is your approach better than the alternatives?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Drawbacks
      description: What are the disadvantages of this proposal?
      placeholder: |
        - Complexity
        - Breaking changes
        - Performance impact
        - Maintenance burden
    validations:
      required: false
  - type: textarea
    attributes:
      label: Unresolved Questions
      description: What aspects need further discussion?
      placeholder: What parts of the design need community input?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Impact Assessment
      options:
        - label: This is a breaking change
        - label: This requires documentation updates
        - label: This affects the CLI interface
        - label: This changes the configuration format
        - label: This impacts performance
    validations:
      required: true